# Generated by Django 4.2.5 on 2023-09-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Berita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("keterangan", models.TextField()),
                ("isi", models.TextField()),
                ("foto", models.ImageField(upload_to="fotoberita/")),
                ("update", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
