# Generated by Django 4.2.5 on 2023-10-02 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_berita"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("alamat", models.TextField()),
                ("email", models.EmailField(default="", max_length=254)),
                ("nohp", models.CharField(max_length=12)),
                ("fb", models.CharField(max_length=200)),
                ("ig", models.CharField(max_length=200)),
                ("tw", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Header",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=200)),
                ("foto", models.ImageField(upload_to="header/")),
            ],
        ),
    ]
