# Generated by Django 4.2.5 on 2023-10-04 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_footer_header"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrakataKepalaSekolahsmp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("keterangan", models.TextField()),
                ("foto", models.ImageField(upload_to="foto/")),
            ],
        ),
    ]
