# Generated by Django 4.2.5 on 2023-10-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_rename_foto_prakatakepalasekolahsmp_fotosmp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kurikulum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrestasiSekolah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_lengkap", models.CharField(max_length=49)),
                ("kelas_jurusan", models.CharField(max_length=50)),
                ("nama_lomba", models.CharField(max_length=50)),
                ("tingkat_kejuaraan", models.CharField(max_length=100)),
                ("juara", models.CharField(max_length=50)),
                ("tanggal_pelaksanaan", models.CharField(max_length=20)),
                ("tempat_penyelenggaraan", models.CharField(max_length=255)),
            ],
        ),
    ]
