# Generated by Django 4.2.5 on 2023-10-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_kurikulum_prestasisekolah"),
    ]

    operations = [
        migrations.AddField(
            model_name="kurikulum",
            name="judul",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="kurikulum",
            name="keterangan",
            field=models.TextField(default=""),
        ),
    ]
