# Generated by Django 4.2.5 on 2023-10-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_kurikulum_judul_kurikulum_keterangan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Runningtext",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
            ],
        ),
    ]
