# Generated by Django 4.2.5 on 2023-10-11 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_runningtext"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jadwal", models.DateTimeField(auto_created=True)),
                ("judul", models.CharField(max_length=255)),
                ("kegiatan", models.TextField()),
            ],
        ),
    ]
