# Generated by Django 4.2.5 on 2023-10-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_agenda"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenda", name="jadwal", field=models.DateTimeField(null=True),
        ),
    ]
