# Generated by Django 4.2.5 on 2023-10-11 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_alter_agenda_jadwal"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramKerja",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("isi", models.TextField()),
            ],
        ),
    ]
