# Generated by Django 4.2.5 on 2023-10-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0011_programkerja"),
    ]

    operations = [
        migrations.CreateModel(
            name="Download",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("judul", models.CharField(max_length=255)),
                ("keterangan", models.TextField()),
                ("files", models.FileField(upload_to="files/")),
            ],
        ),
    ]
