# Generated by Django 4.2.5 on 2023-10-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0012_download"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Judul", models.CharField(max_length=255)),
                ("videos", models.CharField(max_length=255)),
            ],
        ),
    ]
